/**
 * Slack Ingress Adapter
 *
 * Implements Slack HMAC signature verification, parses Events API and
 * Interactivity payloads, and translates them into canonical InboundMessageEnvelopes.
 */

const express = require('express');
const mountSlackRoutes = require('../../shared/routes/slack-interactions.routes');
const { createInboundEnvelope, ENVELOPE_TYPES } = require('../envelope');
const { logToFile } = require('../../shared/utils/logger');

/**
 * Normalizes Slack event into a canonical InboundMessageEnvelope.
 *
 * @param {Object} syntheticReq - Synthetic request generated by Slack adapter
 * @returns {Object} InboundMessageEnvelope
 */
function normalizeSlackEvent(syntheticReq) {
  const metaShape = syntheticReq?.body?.entry?.[0]?.changes?.[0]?.value?.messages?.[0] || syntheticReq?.body;

  const type = metaShape?.type === 'text'
    ? ENVELOPE_TYPES.TEXT
    : metaShape?.interactive?.type === 'button_reply'
    ? ENVELOPE_TYPES.INTERACTIVE_BUTTON
    : ENVELOPE_TYPES.UNKNOWN;

  return createInboundEnvelope({
    id: metaShape?.id || `slack_${Date.now()}`,
    channel: 'slack',
    from: metaShape?.from || '',
    timestamp: metaShape?.timestamp || Math.floor(Date.now() / 1000),
    type,
    payload: {
      text: metaShape?.text?.body,
      actionId: metaShape?.interactive?.button_reply?.id
    },
    metadata: {
      rawMetaShape: metaShape
    },
    rawBody: syntheticReq?.body
  });
}

/**
 * Creates Slack Express router wired to the IngressDispatcher.
 *
 * @param {Object} dispatcher - IngressDispatcher instance
 * @returns {express.Router} Configured router for /api/slack sub-paths
 */
function createSlackRouter(dispatcher) {
  const dispatchBridge = async (syntheticReq, syntheticRes) => {
    try {
      const envelope = normalizeSlackEvent(syntheticReq);

      if (dispatcher) {
        await dispatcher.dispatch(envelope, {
          req: syntheticReq,
          res: syntheticRes,
          channel: 'slack'
        });
      }
    } catch (error) {
      logToFile('❌ Error in Slack gateway dispatcher bridge', { error: error.message });
    }
  };

  return mountSlackRoutes(dispatchBridge);
}

module.exports = {
  normalizeSlackEvent,
  createSlackRouter
};
