-- Migration: Create BYOF tables
-- Purpose: Build Your Own Feature - conversational bug reporting and feature planning
-- Date: December 31, 2025
-- ============================================================================

-- Enable pgvector extension for duplicate detection (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- BYOF Sessions (conversations)
CREATE TABLE IF NOT EXISTS byof_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES dashboard_users(id) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL CHECK (type IN ('bug', 'feature')),
  title TEXT,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'plan_ready', 'closed')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- BYOF Messages (conversation history)
CREATE TABLE IF NOT EXISTS byof_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES byof_sessions(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  attachments JSONB DEFAULT '[]',  -- screenshots, files
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- BYOF Plans (generated implementation plans)
CREATE TABLE IF NOT EXISTS byof_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES byof_sessions(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,  -- Markdown content
  affected_files TEXT[] DEFAULT '{}',
  summary_embedding VECTOR(1536),  -- For duplicate detection (OpenAI embeddings)
  -- Two-stage status: staging_live and production_live track deployment
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'in_progress', 'staging_live', 'production_live', 'rejected')),
  pr_url TEXT,  -- GitHub PR link (must target staging branch)
  approved_by UUID REFERENCES dashboard_users(id),
  approved_at TIMESTAMPTZ,
  staging_merged_at TIMESTAMPTZ,  -- When merged to staging
  completed_at TIMESTAMPTZ,       -- When merged to production (done)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- BYOF Approval Log (audit trail)
CREATE TABLE IF NOT EXISTS byof_approval_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id UUID NOT NULL REFERENCES byof_plans(id) ON DELETE CASCADE,
  action VARCHAR(20) NOT NULL CHECK (action IN ('approved', 'rejected')),
  performed_by UUID NOT NULL REFERENCES dashboard_users(id),
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_byof_sessions_user ON byof_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_byof_sessions_status ON byof_sessions(status);
CREATE INDEX IF NOT EXISTS idx_byof_messages_session ON byof_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_byof_messages_created ON byof_messages(created_at);
CREATE INDEX IF NOT EXISTS idx_byof_plans_session ON byof_plans(session_id);
CREATE INDEX IF NOT EXISTS idx_byof_plans_status ON byof_plans(status);
CREATE INDEX IF NOT EXISTS idx_byof_plans_pr ON byof_plans(pr_url) WHERE pr_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_byof_approval_log_plan ON byof_approval_log(plan_id);

-- Vector search index for duplicate detection (requires pgvector)
-- Note: ivfflat requires at least 1 row to build, so we use hnsw instead
CREATE INDEX IF NOT EXISTS idx_byof_plans_embedding ON byof_plans
USING hnsw (summary_embedding vector_cosine_ops);

-- Comments for documentation
COMMENT ON TABLE byof_sessions IS 'BYOF conversation sessions for bug reports and feature requests';
COMMENT ON TABLE byof_messages IS 'Messages in BYOF conversation sessions';
COMMENT ON TABLE byof_plans IS 'Implementation plans generated by BYOF AI';
COMMENT ON TABLE byof_approval_log IS 'Audit trail for plan approvals and rejections';

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_byof_session_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
DROP TRIGGER IF EXISTS trigger_update_byof_session_timestamp ON byof_sessions;
CREATE TRIGGER trigger_update_byof_session_timestamp
  BEFORE UPDATE ON byof_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_byof_session_timestamp();

-- Grant permissions
GRANT ALL ON byof_sessions TO service_role;
GRANT ALL ON byof_messages TO service_role;
GRANT ALL ON byof_plans TO service_role;
GRANT ALL ON byof_approval_log TO service_role;

-- Rollback script (for reference):
-- DROP TABLE IF EXISTS byof_approval_log;
-- DROP TABLE IF EXISTS byof_plans;
-- DROP TABLE IF EXISTS byof_messages;
-- DROP TABLE IF EXISTS byof_sessions;
-- DROP FUNCTION IF EXISTS update_byof_session_timestamp();
